TEACHER_POSITION, STUDENT_POSITION, PARENTS_POSITION, ORGANIZATION_POSITION = range(4)
USER_POSITIONS = (
    (TEACHER_POSITION, 'teacher'),
    (STUDENT_POSITION, 'student'),
    (PARENTS_POSITION, 'parents'),
    (ORGANIZATION_POSITION, 'organization administrator'),
)